# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('two_side_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
