# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_side_app', '0002_auto_20170114_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docnum',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
